version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule: { interval: weekly }
    groups:
      gomod:
        patterns:
          - "*"
      gomod-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
    groups:
      github-actions:
        patterns:
          - "*"
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
