package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/downpipes-io/downpipe/internal/crypto"
	"github.com/downpipes-io/downpipe/internal/format"
)

// These run against testdata/custody, the 3-of-4 ceremony generated by the console's own custody code,
// so what is proven here is the artefacts customers actually hold, not a Go-side re-implementation.

func sharesOnly() *identityFlags {
	return &identityFlags{
		shares:   stringList{fixture("share-1.txt"), fixture("share-3.txt"), fixture("share-4.txt")},
		envelope: fixture("wrapped-identity.txt"),
	}
}

// keyBytes flattens an identity to comparable material. Comparing the parsed structs directly would
// compare pointers, which is true of any two distinct keys and so would prove nothing.
func keyBytes(t *testing.T, k *crypto.HybridKEMPrivate) []byte {
	t.Helper()
	if k == nil || k.X25519 == nil || k.MLKEM == nil {
		t.Fatal("identity is missing a half")
	}
	return append(append([]byte(nil), k.X25519.Bytes()...), k.MLKEM.Bytes()...)
}

// The claim the whole change rests on: an M-of-N custody arrangement resolves to the SAME key a
// single-file arrangement does, so every command that takes an identity now works from shares directly.
func TestSharesResolveToTheSameIdentityAsTheKeyFile(t *testing.T) {
	fromShares, err := sharesOnly().resolve()
	if err != nil {
		t.Fatalf("resolve from shares: %v", err)
	}
	fromFile, err := (&identityFlags{path: fixture("expected-identity.key")}).resolve()
	if err != nil {
		t.Fatalf("resolve from file: %v", err)
	}
	if !bytes.Equal(keyBytes(t, fromShares), keyBytes(t, fromFile)) {
		t.Fatal("the key recovered from shares differs from the key in the identity file")
	}
}

// The reason for doing it in memory at all. If this regresses, split custody quietly goes back to
// meaning "write the complete break-glass key to one operator's disk and hope they delete it".
func TestResolvingFromSharesWritesNoFile(t *testing.T) {
	dir := t.TempDir()
	before, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	// Resolve with the process CWD inside the empty dir, so a stray relative-path write (identity.key is
	// the default --out of recombine, and that is exactly the mistake worth catching) lands here.
	f := &identityFlags{
		shares:   stringList{filepath.Join(wd, custodyDir, "share-1.txt"), filepath.Join(wd, custodyDir, "share-3.txt"), filepath.Join(wd, custodyDir, "share-4.txt")},
		envelope: filepath.Join(wd, custodyDir, "wrapped-identity.txt"),
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })

	if _, err := f.resolve(); err != nil {
		t.Fatalf("resolve: %v", err)
	}
	after, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(after) != len(before) {
		names := make([]string, 0, len(after))
		for _, e := range after {
			names = append(names, e.Name())
		}
		t.Fatalf("resolving from shares created %d file(s): %v", len(after)-len(before), names)
	}
}

// Both sources at once is refused rather than resolved by precedence. An operator who passes both has a
// belief about which key is in use, and a silent rule would be right only half the time.
func TestSuppliedBothSourcesIsRefused(t *testing.T) {
	f := sharesOnly()
	f.path = fixture("expected-identity.key")
	_, err := f.resolve()
	if err == nil {
		t.Fatal("want a refusal when --identity and the custody artefacts are both supplied")
	}
	wantExit(t, err, format.ExitUsage)
}

// Shares without the envelope cannot decrypt anything, so say which artefact is missing rather than
// failing later inside the recombine.
func TestSharesWithoutAnEnvelopeAreRefusedByName(t *testing.T) {
	f := sharesOnly()
	f.envelope = ""
	_, err := f.resolve()
	if err == nil {
		t.Fatal("want a refusal when shares are supplied with no envelope")
	}
	wantExit(t, err, format.ExitUsage)
}

// No source at all must name every source, since this is the message an operator sees first.
func TestNoIdentitySourceNamesTheAlternatives(t *testing.T) {
	_, err := (&identityFlags{}).resolve()
	if err == nil {
		t.Fatal("want a refusal when no identity source is supplied")
	}
	wantExit(t, err, format.ExitUsage)
	for _, want := range []string{"--identity", "--share", "--envelope"} {
		if !bytes.Contains([]byte(err.Error()), []byte(want)) {
			t.Errorf("the no-source message does not mention %s: %v", want, err)
		}
	}
}

// Below the ceremony's threshold must fail, and must fail on the threshold rather than by producing a
// wrong key that then fails somewhere less legible.
func TestBelowThresholdFromSharesFails(t *testing.T) {
	f := &identityFlags{
		shares:   stringList{fixture("share-1.txt"), fixture("share-3.txt")},
		envelope: fixture("wrapped-identity.txt"),
	}
	if _, err := f.resolve(); err == nil {
		t.Fatal("2 of a 3-of-4 ceremony must not resolve")
	}
}

// The wrapping-key artefact is the other half of the custody arrangement and must work the same way.
func TestWrappingKeyResolvesInMemoryToo(t *testing.T) {
	f := &identityFlags{wrappingKey: fixture("wrapping-key.txt"), envelope: fixture("wrapped-identity.txt")}
	got, err := f.resolve()
	if err != nil {
		t.Fatalf("resolve from the wrapping key: %v", err)
	}
	want, err := (&identityFlags{path: fixture("expected-identity.key")}).resolve()
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(keyBytes(t, got), keyBytes(t, want)) {
		t.Fatal("the wrapping-key route recovered a different key")
	}
}

// loadAndVerifier is what the commands actually call, so the share route has to reach the end of it.
func TestLoadAndVerifierWorksFromShares(t *testing.T) {
	dir := t.TempDir()
	signer := filepath.Join(dir, "signer.pub")
	_, verifier, err := crypto.GenerateHybridSigner()
	if err != nil {
		t.Fatal(err)
	}
	if err := writeKeyFile(signer, labelSignerPublic, crypto.MarshalVerifier(verifier)); err != nil {
		t.Fatal(err)
	}
	id, ver, err := sharesOnly().loadAndVerifier(signer)
	if err != nil {
		t.Fatalf("loadAndVerifier from shares: %v", err)
	}
	if id == nil || ver == nil {
		t.Fatal("want both an identity and a verifier")
	}
}

// The freshness hint must not be offered by a command that has no acknowledgement to offer. Advice an
// operator cannot follow is worse than none: doing as they are told yields "flag provided but not
// defined", and the next hint the tool gives them is worth less.
//
// BOTH FLAGS ARE PROBED, not either. The hint now chooses between --allow-stale and
// --allow-unverified-runlog by what the reader actually found, so a command carrying only one of the
// pair would still be handed the sentence naming the other, and an operator following it would get
// "flag provided but not defined" from the very message written to stop that happening.
//
// THE PROBE COVERS THE WHOLE DISPATCH. It used to name four commands, and its helper returned a nil
// error for every command it did not name, so an unnamed command read as one that accepts the flag and
// nothing checked it either way. Proven by adding an --allow-stale flag to attest.go and leaving the
// map alone: attest accepted the flag, the hint was withheld from it, and the whole cmd/downpipe
// package stayed green. The command set now comes from the parsed dispatch switch, so a command added
// next month is probed without anyone remembering to add it here.
func TestOnlyCommandsWithAFreshnessOverrideAreOfferedTheFreshnessHint(t *testing.T) {
	silenceOutput(t)
	for _, cmd := range []string{"verify", "restore"} {
		if !acceptsFreshnessOverride[cmd] {
			t.Errorf("%s defines the freshness acknowledgements, so it should be offered the hint", cmd)
		}
	}

	dispatch := map[string]bool{}
	builtin := map[string]bool{}
	for _, c := range wantBuiltins {
		builtin[c] = true
	}
	// Constructing a FlagSet here and asserting it has the flag we just put on it would prove nothing,
	// so this drives the ACTUAL command dispatch with --allow-stale. Every command is called with
	// arguments that fail for some other reason; the only thing read is whether the failure was "flag
	// provided but not defined", which the flag package reports before the command does any work.
	for _, cmd := range dispatchCases(t) {
		dispatch[cmd] = true
		if builtin[cmd] {
			// The built-ins parse no flags at all, so the probe cannot tell an accepted flag from an
			// ignored one. Offering them the hint would still be wrong, and that is checked below.
			continue
		}
		for _, flagName := range []string{"allow-stale", "allow-unverified-runlog"} {
			out := captureStderr(t, func() {
				_ = run([]string{cmd, "--" + flagName, "--archive", string(filepath.Separator) + "nonexistent-downpipe-probe"})
			})
			accepts := !strings.Contains(out, "flag provided but not defined: -"+flagName)
			switch {
			case accepts && !acceptsFreshnessOverride[cmd]:
				t.Errorf("%s accepts --%s but acceptsFreshnessOverride does not list it, so the freshness hint is withheld from a command that could act on it", cmd, flagName)
			case !accepts && acceptsFreshnessOverride[cmd]:
				t.Errorf("%s is offered the freshness hint but rejects --%s, so an operator doing as they are told gets \"flag provided but not defined\"", cmd, flagName)
			}
		}
	}

	for cmd, offered := range acceptsFreshnessOverride {
		if !offered {
			continue
		}
		if builtin[cmd] {
			t.Errorf("%s is a built-in that parses no flags, so offering it the freshness hint sends an operator to a flag that does not exist", cmd)
		}
		if !dispatch[cmd] {
			t.Errorf("acceptsFreshnessOverride lists %q, which the dispatch switch does not carry; the hint is keyed on a command that cannot be run", cmd)
		}
	}
}

// The engine and this tool each carry their own RECOVER.md text, because they are separate repositories
// and the bundle content is not normative (every archive verifies its bundle against the SHA384SUMS
// written in the same run, so the copies never have to match byte for byte). They must still SAY the
// same thing. This is the document a customer reads mid-recovery with nothing else to go on, and the
// two had already drifted once: the selftest's copy still said "run:" and omitted the custody route
// entirely, so a selftest was demonstrating a recovery that differed from the one real archives carry.
//
// Rather than pin the whole text, which would make every wording improvement a two-repo lockstep edit,
// this asserts the load-bearing claims are present. A copy that loses one of these is teaching a
// split-custody customer that their shares are no use.
func TestTheSelftestRecoveryTextTeachesTheSameRecoveryAsARealArchive(t *testing.T) {
	dir := t.TempDir()
	sig, _, err := crypto.GenerateHybridSigner()
	if err != nil {
		t.Fatal(err)
	}
	if err := writeSelftestBundle(dir, sig); err != nil {
		t.Fatalf("write selftest bundle: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "_RECOVERY", "downpipe", "0.1.0", "RECOVER.md"))
	if err != nil {
		t.Fatalf("read the selftest RECOVER.md: %v", err)
	}
	// HTML COMMENTS ARE NOT WHAT THE CUSTOMER READS. A substring search cannot see a comment around the
	// text it finds. Parking the whole custody paragraph in an <!-- --> block left every claim below
	// present in the bytes and none of it visible in the rendered document, which is the exact outcome
	// this test exists to prevent: a split-custody holder opening RECOVER.md mid-recovery is told
	// nothing about their shares. Proven against this repository.
	text := stripHTMLComments(string(got))
	for _, claim := range []string{
		"downpipe restore",
		"--identity identity.key",
		// The custody route. Its absence is the drift that mattered.
		"--share",
		"--envelope",
		"M-of-N",
		"no complete key is written to disk",
		"neither Cloudflare nor the vendor",
		// Ported from the engine's own parity check (engine/test/validate-format-prims.ts) when the
		// engine copy landed. Each is a claim whose absence sent a customer down a route
		// that does not reach their data: without --apply the printed restore exits 0 and writes
		// nothing, and without the --signer sentence an operator reading only the prose builds a
		// one-file kit that cannot recover.
		"--apply",
		"Both restore and verify require --signer",
		"a kit holding only the identity cannot recover",
		// The keyless step that answers "which run do I ask for". The document asked for a <runId>
		// and never said where one comes from.
		"downpipe keys --which",
	} {
		if !strings.Contains(text, claim) {
			t.Errorf("the selftest RECOVER.md no longer mentions %q, so it has drifted from the engine's copy:\n%s", claim, text)
		}
	}
}

// stripHTMLComments blanks every <!-- --> span, so only what a reader of the rendered document would
// see is searched. It is deliberately total: an unterminated comment swallows the rest of the text
// rather than being ignored, because an unterminated comment hides the rest of the document too.
func stripHTMLComments(s string) string {
	var b strings.Builder
	for {
		i := strings.Index(s, "<!--")
		if i < 0 {
			b.WriteString(s)
			return b.String()
		}
		b.WriteString(s[:i])
		rest := s[i+4:]
		j := strings.Index(rest, "-->")
		if j < 0 {
			return b.String()
		}
		s = rest[j+3:]
	}
}

// The help text lists the exit codes because this tool is for the case where the platform is unreachable:
// a person doing an offline recovery has the binary and may not have the documentation. A list that drifts
// from the real codes is worse than none, since a recovery script is written against what it says.
//
// Asserted against the format package's constants rather than against a second hand-written list, so the
// only way to pass is for the help to agree with the codes the tool actually returns.
func TestHelpListsEveryExitCode(t *testing.T) {
	var out bytes.Buffer
	prior := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	usage()
	_ = w.Close()
	os.Stdout = prior
	if _, err := out.ReadFrom(r); err != nil {
		t.Fatal(err)
	}
	help := out.String()

	// The codes come from the parsed source of the format package, not from a list written here.
	// ExitCustody was returned by the reader but never listed in the help, which is how it came to share
	// 9 with ExitUnwritten unnoticed, and a hand list repeats that failure the day someone adds a code
	// and does not think of the help. Proven: adding ExitTruncated = 12 to errors.go and pinning it
	// properly in the format package left this test green with a code the reader can return and the help
	// never mentions.
	codes := declaredExitCodesFromFormat(t)
	if len(codes) < 11 {
		t.Fatalf("found only %d exit codes in the format package; the scan has probably stopped seeing them", len(codes))
	}
	names := make([]string, 0, len(codes))
	for name := range codes {
		names = append(names, name)
	}
	sort.Strings(names)

	seen := map[string]string{}
	for _, name := range names {
		code := codes[name]
		line := exitCodeLine(help, code)
		if line == "" {
			t.Errorf("help does not list exit code %d (%s); a recovery script is written against this list", code, name)
			continue
		}
		// A listed code with no real description is worse than an absent one: it looks answered. The first
		// version of this test checked only that the NUMBER appeared in list form, and a sabotage replacing
		// the description with "(sabotage)" passed it.
		if len(line) < 20 {
			t.Errorf("exit code %d (%s) is listed with no useful description: %q", code, name, line)
		}
		if prev, dup := seen[line]; dup {
			t.Errorf("exit code %d (%s) repeats the description of %s: %q", code, name, prev, line)
		}
		seen[line] = name
	}
	// The advisory distinction is the part a script gets wrong: 8 and 9 mean the restore RAN and fell
	// short, so treating any non-zero exit as failure would discard a restore that mostly succeeded.
	if !strings.Contains(help, "ADVISORY") {
		t.Error("help does not distinguish the advisory codes from the hard failures")
	}
	// Guard the guard: a help text that lost its exit-code section entirely would fail every check above
	// for the same reason, which reads as nine problems rather than one.
	if !strings.Contains(help, "Exit codes") {
		t.Fatal("the help text has no exit-code section at all")
	}
}

// declaredExitCodesFromFormat reads every Exit* constant out of the parsed internal/format package, by
// name and value. It is deliberately the same shape as that package's own gate: accounting is TOTAL, so
// a constant whose value this cannot resolve to an integer fails the test naming the position rather
// than dropping out of the required set and leaving the help unchecked for it.
func declaredExitCodesFromFormat(t *testing.T) map[string]int {
	t.Helper()
	dir := filepath.Join("..", "..", "internal", "format")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read the format package: %v", err)
	}
	fset := token.NewFileSet()
	out := map[string]int{}
	refs := map[string]string{}
	positions := map[string]string{}
	files := 0
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, perr := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if perr != nil {
			t.Fatalf("cannot parse %s, so its exit codes cannot be accounted for: %v", name, perr)
		}
		files++
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, s := range gd.Specs {
				vs, ok := s.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, id := range vs.Names {
					if !strings.HasPrefix(id.Name, "Exit") {
						continue
					}
					pos := fset.Position(id.Pos()).String()
					positions[id.Name] = pos
					if i >= len(vs.Values) {
						t.Fatalf("%s at %s has no value of its own, so the help cannot be checked against it", id.Name, pos)
					}
					switch v := vs.Values[i].(type) {
					case *ast.BasicLit:
						n, cerr := strconv.Atoi(v.Value)
						if cerr != nil {
							t.Fatalf("%s at %s has unreadable value %q: %v", id.Name, pos, v.Value, cerr)
						}
						out[id.Name] = n
					case *ast.Ident:
						refs[id.Name] = v.Name
					default:
						t.Fatalf("%s at %s is set from an expression this test cannot resolve to a number", id.Name, pos)
					}
				}
			}
		}
	}
	if files < 10 {
		t.Fatalf("expected the format package's source files, found only %d. Has the layout moved?", files)
	}
	for name, ref := range refs {
		n, ok := out[ref]
		if !ok {
			t.Fatalf("%s at %s is set from %s, which is not an Exit constant with a literal value", name, positions[name], ref)
		}
		out[name] = n
	}
	return out
}

// exitCodeLine returns the description on the help's list line for code, or "" when the code is not listed.
// It matches the two-space list form the help uses so a bare mention of the digit elsewhere in the prose
// cannot satisfy the caller.
func exitCodeLine(help string, code int) string {
	prefix := fmt.Sprintf("\n  %-2d  ", code)
	i := strings.Index(help, prefix)
	if i < 0 {
		return ""
	}
	rest := help[i+len(prefix):]
	if j := strings.IndexByte(rest, '\n'); j >= 0 {
		rest = rest[:j]
	}
	return strings.TrimSpace(rest)
}
