package main

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/downpipes-io/downpipe/internal/format"
)

// The fixtures under testdata/custody were generated by RUNNING the console's own
// custody code (shamir split, WebCrypto AES-256-GCM envelope, artefact serialisers)
// over a real keygen identity, so these tests prove byte-compatibility with the
// artefacts customers actually hold. The ceremony is 3-of-4.
const custodyDir = "testdata/custody"

func fixture(name string) string { return filepath.Join(custodyDir, name) }

func runRecombine(t *testing.T, args ...string) (string, error) {
	t.Helper()
	out := filepath.Join(t.TempDir(), "identity.key")
	err := cmdRecombine(context.Background(), append(args, "--out", out))
	return out, err
}

func wantExit(t *testing.T, err error, code int) {
	t.Helper()
	var ee *format.ExitError
	if !errors.As(err, &ee) || ee.Code != code {
		t.Fatalf("want exit %d, got %v", code, err)
	}
}

func assertRecovered(t *testing.T, out string) {
	t.Helper()
	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	want, err := os.ReadFile(fixture("expected-identity.key"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(want) {
		t.Fatal("recovered identity.key does not byte-match the console's plaintext")
	}
	fi, err := os.Stat(out)
	if err != nil {
		t.Fatal(err)
	}
	if fi.Mode().Perm() != 0o600 {
		t.Fatalf("identity.key mode %v, want 0600", fi.Mode().Perm())
	}
}

func TestRecombineFromLabelledShares(t *testing.T) {
	out, err := runRecombine(t,
		"--share", fixture("share-1.txt"),
		"--share", fixture("share-3.txt"),
		"--share", fixture("share-4.txt"),
		"--envelope", fixture("wrapped-identity.txt"))
	if err != nil {
		t.Fatalf("recombine: %v", err)
	}
	assertRecovered(t, out)
}

func TestRecombineMixesLabelledAndEmailedShares(t *testing.T) {
	// raw-share-2.txt is the bare base64url body a custodian receives by email.
	out, err := runRecombine(t,
		"--share", fixture("share-1.txt"),
		"--share", fixture("raw-share-2.txt"),
		"--share", fixture("share-4.txt"),
		"--envelope", fixture("wrapped-identity.txt"))
	if err != nil {
		t.Fatalf("recombine: %v", err)
	}
	assertRecovered(t, out)
}

func TestRecombineFromWrappingKey(t *testing.T) {
	out, err := runRecombine(t,
		"--wrapping-key", fixture("wrapping-key.txt"),
		"--envelope", fixture("wrapped-identity.txt"))
	if err != nil {
		t.Fatalf("recombine: %v", err)
	}
	assertRecovered(t, out)
}

// TestRecombineDedupesAnIdenticalDuplicate accepts four inputs of which two are the same
// custodian's share, and the acceptance is deliberate: a custodian's share arrives as a
// labelled file AND as the body of the email that delivered it, so a ceremony convener holding
// both has one custodian, not two, and refusing would strand a recovery over a clerical
// double-paste. The decision is only safe because the two bodies are IDENTICAL -- a
// same-index different-body pair is a different question and is refused elsewhere.
//
// The count is what the operator's threshold arithmetic rests on, so the permissive path must
// SAY it dropped one. Four inputs recovering a 3-of-N secret silently would leave the convener
// believing four custodians took part, and the next ceremony would be planned on that belief.
// The notice is therefore asserted here, next to the acceptance it pays for; without it this
// test would be recording that a duplicate is tolerated and saying nothing about the operator
// being told.
func TestRecombineDedupesAnIdenticalDuplicate(t *testing.T) {
	// share-2 supplied twice (labelled file + its emailed body) plus two more: four
	// inputs, three distinct, threshold met.
	var out string
	var err error
	_, stderr := captureOutput(t, func() {
		out, err = runRecombine(t,
			"--share", fixture("share-2.txt"),
			"--share", fixture("raw-share-2.txt"),
			"--share", fixture("share-1.txt"),
			"--share", fixture("share-3.txt"),
			"--envelope", fixture("wrapped-identity.txt"))
	})
	if err != nil {
		t.Fatalf("recombine: %v", err)
	}
	assertRecovered(t, out)
	if !strings.Contains(stderr, "dropped a duplicate of share") {
		t.Errorf("a dropped duplicate must be reported, or four inputs recovering a 3-of-N secret reads as four custodians:\n%s", stderr)
	}
	if !strings.Contains(stderr, "the same custodian was supplied twice") {
		t.Errorf("the notice must name WHY the input was dropped, so the convener can tell a double-paste from a missing custodian:\n%s", stderr)
	}
}

func TestRecombineBelowThresholdFailsEarly(t *testing.T) {
	_, err := runRecombine(t,
		"--share", fixture("share-1.txt"),
		"--share", fixture("share-2.txt"),
		"--envelope", fixture("wrapped-identity.txt"))
	wantExit(t, err, format.ExitUsage)
	if !strings.Contains(err.Error(), "need 3") {
		t.Fatalf("the message must state need/got: %v", err)
	}
}

func TestRecombineWrongShareFailsTheChecksum(t *testing.T) {
	// Flip one byte inside share-3's body: recombination succeeds structurally but the
	// public checksum catches the wrong key BEFORE the decrypt.
	text, err := os.ReadFile(fixture("share-3.txt"))
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(string(text), "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "share ") {
			body := strings.TrimPrefix(l, "share ")
			mutated := []byte(body)
			if mutated[10] != 'A' {
				mutated[10] = 'A'
			} else {
				mutated[10] = 'B'
			}
			lines[i] = "share " + string(mutated)
		}
	}
	bad := filepath.Join(t.TempDir(), "share-3-bad.txt")
	if err := os.WriteFile(bad, []byte(strings.Join(lines, "\n")), 0o600); err != nil {
		t.Fatal(err)
	}
	_, rerr := runRecombine(t,
		"--share", fixture("share-1.txt"),
		"--share", bad,
		"--share", fixture("share-4.txt"),
		"--envelope", fixture("wrapped-identity.txt"))
	wantExit(t, rerr, format.ExitCustody)
	if !strings.Contains(rerr.Error(), "checksum") {
		t.Fatalf("the failure must name the checksum: %v", rerr)
	}
}

func TestRecombineAllRawNeedsNoChecksumAndDecryptDecides(t *testing.T) {
	// An all-emailed set has no labelled file, no checksum and no threshold: with the
	// hint and the right shares the authenticated decrypt is the acceptance check.
	raw := func(t *testing.T, n string) string {
		t.Helper()
		text, err := os.ReadFile(fixture(n))
		if err != nil {
			t.Fatal(err)
		}
		var body string
		for _, l := range strings.Split(string(text), "\n") {
			if strings.HasPrefix(l, "share ") {
				body = strings.TrimPrefix(l, "share ")
			}
		}
		p := filepath.Join(t.TempDir(), n+".raw")
		if err := os.WriteFile(p, []byte(body+"\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		return p
	}
	out, err := runRecombine(t,
		"--share", raw(t, "share-1.txt"),
		"--share", raw(t, "share-2.txt"),
		"--share", raw(t, "share-3.txt"),
		"--threshold", "3",
		"--envelope", fixture("wrapped-identity.txt"))
	if err != nil {
		t.Fatalf("recombine: %v", err)
	}
	assertRecovered(t, out)

	// Below the hint: fail early with need/got rather than a confusing decrypt error.
	_, err = runRecombine(t,
		"--share", raw(t, "share-1.txt"),
		"--share", raw(t, "share-2.txt"),
		"--threshold", "3",
		"--envelope", fixture("wrapped-identity.txt"))
	wantExit(t, err, format.ExitUsage)
}

func TestRecombineTamperedCiphertextFailsTheDecrypt(t *testing.T) {
	text, err := os.ReadFile(fixture("wrapped-identity.txt"))
	if err != nil {
		t.Fatal(err)
	}
	mutated := strings.Replace(string(text), "ciphertext ", "ciphertext A", 1)
	bad := filepath.Join(t.TempDir(), "wrapped-bad.txt")
	if err := os.WriteFile(bad, []byte(mutated), 0o600); err != nil {
		t.Fatal(err)
	}
	_, rerr := runRecombine(t,
		"--share", fixture("share-1.txt"),
		"--share", fixture("share-2.txt"),
		"--share", fixture("share-3.txt"),
		"--envelope", bad)
	wantExit(t, rerr, format.ExitCustody)
}

func TestRecombineUsageRefusals(t *testing.T) {
	// The wrong artefact kind for --share: a precise magic error, exit 6.
	_, err := runRecombine(t,
		"--share", fixture("wrapping-key.txt"),
		"--envelope", fixture("wrapped-identity.txt"))
	wantExit(t, err, format.ExitUsage)

	// Shares and a wrapping key together.
	_, err = runRecombine(t,
		"--share", fixture("share-1.txt"),
		"--wrapping-key", fixture("wrapping-key.txt"),
		"--envelope", fixture("wrapped-identity.txt"))
	wantExit(t, err, format.ExitUsage)

	// A credential-id envelope is a security-key posture, not recombinable offline.
	env, rerr := os.ReadFile(fixture("wrapped-identity.txt"))
	if rerr != nil {
		t.Fatal(rerr)
	}
	cred := string(env) + "credential-id AAAA\n"
	credPath := filepath.Join(t.TempDir(), "wrapped-cred.txt")
	if err := os.WriteFile(credPath, []byte(cred), 0o600); err != nil {
		t.Fatal(err)
	}
	_, err = runRecombine(t,
		"--share", fixture("share-1.txt"),
		"--share", fixture("share-2.txt"),
		"--share", fixture("share-3.txt"),
		"--envelope", credPath)
	wantExit(t, err, format.ExitUsage)
	if !strings.Contains(err.Error(), "security key") {
		t.Fatalf("the message must explain the security-key posture: %v", err)
	}
}

func TestRecombineRefusesToOverwrite(t *testing.T) {
	out := filepath.Join(t.TempDir(), "identity.key")
	if err := os.WriteFile(out, []byte("precious"), 0o600); err != nil {
		t.Fatal(err)
	}
	err := cmdRecombine(context.Background(), []string{
		"--share", fixture("share-1.txt"),
		"--share", fixture("share-2.txt"),
		"--share", fixture("share-3.txt"),
		"--envelope", fixture("wrapped-identity.txt"),
		"--out", out,
	})
	wantExit(t, err, format.ExitUsage)
	got, rerr := os.ReadFile(out)
	if rerr != nil || string(got) != "precious" {
		t.Fatal("the existing file must be untouched")
	}
}
